<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Walkingtree-PC" name="Testng_concept.basic_testng" tests="9" failures="1" timestamp="21 Feb 2018 09:02:29 GMT" time="0.034" errors="0">
  <testcase name="beforeTest" time="0.002" classname="Testng_concept.basic_testng"/>
  <testcase name="afterSuite" time="0.001" classname="Testng_concept.basic_testng"/>
  <testcase name="afterClass" time="0.002" classname="Testng_concept.basic_testng"/>
  <testcase name="afterTest" time="0.001" classname="Testng_concept.basic_testng"/>
  <testcase name="TestCase1" time="0.017" classname="Testng_concept.basic_testng"/>
  <testcase name="afterMethod" time="0.002" classname="Testng_concept.basic_testng"/>
  <testcase name="beforeMethod" time="0.007" classname="Testng_concept.basic_testng">
    <failure type="java.lang.AssertionError" message="Actual name is not matching with expected  expected [sohan] but found [Murari]">
      <![CDATA[java.lang.AssertionError: Actual name is not matching with expected  expected [sohan] but found [Murari]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at Testng_concept.basic_testng.beforeMethod(basic_testng.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeClass" time="0.001" classname="Testng_concept.basic_testng"/>
  <testcase name="beforeSuite" time="0.001" classname="Testng_concept.basic_testng"/>
</testsuite> <!-- Testng_concept.basic_testng -->
